### ISSUE TITLE
My app crashes after installing this module

### ISSUE THREAD

**Issue by meypod** [jd1378/react-native-alarm-module#2]
hi
after installing this module, my app crashes on xiaomi devices the second time I launch the app from the launcher
I don't understand what's the problem
this is the error:
```
Fatal Exception: java.lang.IllegalArgumentException: Could not convert class android.os.UserHandle
```

**Comment by jd1378** [comment]
Luckily I had a xiaomi device around and and I can confirm this, I'll see what I can do

**Comment by jd1378** [comment]
please try out v3.0.0
it contains a breaking change, please check the readme again
but I thought Its a necessary change to simplify the build step
and the crash problem should be gone now
