### ISSUE TITLE
 TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by rashadmiya** [jd1378/react-native-alarm-module#5]
when try to setAlarm this error occur, 

here is my code,

const [lastDate, setLastDate] = useState(new Date(Date.now() + 5 * 1000));

    const setAlarmOnPress = useCallback(() => {
        const newDate = new Date(Date.now() + 5 * 1000);
        setLastDate(newDate);

        setAlarm({
          taskName: 'ShowToastTask', // required
          timestamp: newDate.valueOf(), // required
          type: 'setAlarmClock', // optional
          allowedInForeground: true, // optional 
          wakeup: true, // optional
          keepAwake: false,
          extra: 'something extra', // optional
            
        });
        

        ToastAndroid.show(
            `alarm set for ${newDate.toISOString()}`,
            ToastAndroid.SHORT,
          );

    },[])

    const cancel = useCallback(() => {
        cancelAlarm({
          taskName: 'ShowToastTask',
          timestamp: lastDate.valueOf(),
        });
        ToastAndroid.show(
          `alarm cancelled for ${lastDate.toISOString()}`,
          ToastAndroid.SHORT,
        );
      }, [lastDate])

**Comment by jd1378** [comment]
It's probably an error somewhere else
try to narrow where it's happening
because I could run the example and use the module without error right now

**Comment by jd1378** [comment]
I'm closing this since I got no response
